# Generated by Django 4.1.5 on 2023-02-02 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0003_delete_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deporte',
            old_name='futbol',
            new_name='club',
        ),
    ]
